name: Install Nginx and Show Public IP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Update the package list
        run: sudo apt-get update

      - name: Install Nginx
        run: sudo apt-get install -y nginx

      - name: Start Nginx service
        run: sudo systemctl start nginx

      - name: Show Nginx status
        run: sudo systemctl status nginx

      - name: Show public IP of the runner
        run: curl -s https://ipinfo.io/ip
